title: RainyCanvas
description: a journey about watercolor
url: "https://rainycanvas.github.io"
cover_image: /assets/bg2.png
cover_color: rgb(202, 151, 137)

remote_theme: vszhub/not-pure-poole

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
