title: RainyCanvas
description: a journey about watercolor
url: "https://rainycanvas.github.io"
cover_image: /assets/bg2.png
avatar: /assets/brush_face.png
cover_color: rgb(202, 151, 137)
future: true
paginate: 10

remote_theme: vszhub/not-pure-poole

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
