title: RainyCanvas
description: a journey about watercolor
baseurl: ""
url: "https://rainycanvas.github.io"

remote_theme: vszhub/not-pure-poole

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
