# ----------------------------------------------------------------             
# basic
# ----------------------------------------------------------------
title: "RainyCanvas"
description: "a journey about watercolor"
baseurl: "
url: "https://rainycanvas.github.io"

# ----------------------------------------------------------------
# content
# ----------------------------------------------------------------
permalink: /posts/:title/
theme: minima

# ----------------------------------------------------------------
# other
# ----------------------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
